# fly.toml file generated for nullgrid-site on 2023-06-27T18:36:32+01:00

app = "nullgrid-site"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
processes = []

[build]
  builder = "heroku/buildpacks:20"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
